# import logging
# from pathlib import Path
#
# from jinja2 import FileSystemLoader, Environment, TemplateNotFound
#
# from .discovery import DiscoveryContext
#
# log = logging.getLogger("simple-oop")
#
#
# class CodeGen:
#     generated_file_marker = "// autogenerated by simple-oop\n"
#     tablename_variable = "%tablename"
#
#     def __init__(self, ctx: DiscoveryContext):
#         self.ctx = ctx
#         self.env = Environment(loader=FileSystemLoader(ctx.config.template_directory), autoescape=False)
#
#     def render(self, template, file: Path, variables: dict):
#         file.parent.mkdir(parents=True, exist_ok=True)
#         if file.exists() and not file.read_text().startswith(self.generated_file_marker):
#             log.error(f"Any files generated by simple-oop must start with "
#                       f"\"{self.generated_file_marker}\" otherwise they will "
#                       f"not be overwritten")
#             return
#
#         file.write_text(self.generated_file_marker + template.render(**variables))
#         log.info(f"Generated {file.name}")
#
#     def generate(self, template_name: str):
#         try:
#             template = self.env.get_template(template_name)
#         except TemplateNotFound as e:
#             print(e)
#             return
#
#         if self.tablename_variable in template_name:
#             for tablename in (t for t in self.ctx.types.values() if t.gen_table):
#                 self.render(template, self.ctx.config.output_directory / template_name.replace(self.tablename_variable,
#                                                                                                 tablename.name),
#                             {
#                                 "set": set,
#                                 "tablename": tablename,
#                                 "types": self.ctx.types.values(),
#                                 "objects": [t for t in tablename.indirect_children if t.has_instances]})
#         else:
#             self.render(template, self.ctx.config.output_directory / template_name,
#                         {
#                             "set": set,
#                             "types": self.ctx.types.values(),
#                             "objects": [t for t in self.ctx.types.values() if t.has_instances]})
